### ISSUE TITLE
motion sensor

### ISSUE THREAD

**Issue by czdeee** [peros550/esp-homekit-multiple-sensors#1]
Does the motion  sensor need to connect a Resistance?
i test my motion sensor it doesnt work

**Comment by peros550** [comment]
Hi, can you provide more information on what sensor & board do you have?
In my case I didn't need to connect any resistor. 

Here is a photo (not a very good angle I admit)  of my board with all sensors attached. 

For easier testing of the sensor, I have configured the on board LED to turn on as long as motion sensor detects movement.  This is happening regardless of connected to wifi or pairing with Home app.  Have you connected a led on your board? 

You also might want to check if your sensor is able to change its output logic (3,3V >> 0V or 0V>>3,3V when motion is detected) and try the other logic just to see if that setting helps. 

![img_9545](https://user-images.githubusercontent.com/12878906/43760600-3fdf149a-9a2b-11e8-9846-9a8d16c05090.JPG)
