### ISSUE TITLE
No response after a period of time

### ISSUE THREAD

**Issue by pedroserano** [peros550/esp-homekit-multiple-sensors#3]
Has anyone else been using this program on their esp8266s for a while and eventually have it stop responding in Homekit? Sometimes unplugging and replugging the power fixes it, other times I have to hit the button to reset Homekit pairing.

**Comment by peros550** [comment]
Can you please advise roughly how long did it take for the esp8266 to stop responding? Is it a day , a week? 
Also, if you ever face the same issue again, please check from your device for available Wifi networks and check if the esp8266 went into AP mode. Looking forward for your feedback.

**Comment by pedroserano** [comment]
About a week. This describes the same issue. Looks like it’s fixed with the latest commit of esp-HomeKit. 
https://www.reddit.com/r/ESPHomeKit/comments/88jb0j/memory_leak/

**Comment by peros550** [comment]
I will close the issue. I think it's already fixed. If not, feel free to re-open
