### ISSUE TITLE
DHT 11 sensor is compatible?

### ISSUE THREAD

**Issue by renandw** [peros550/esp-homekit-multiple-sensors#5]
Hi.
I looked in to your example and it is perfect for what I want.
I flashed it and had a few problems. First I couldn’t add it to my Home.app but all the sensors was attached to it. I tried again with no sensors and configured it to the app. But then just the air conditioner and the temperature/umidity sensor show “no response”. Again I tried without all sensors and found out that when I plugged the DHT11 sensor it stops working. Motion sensor works fine.
Anybody getting the same results? Thanks in advance

**Comment by peros550** [comment]
If you would like to use DHT11 , find the following line in the code: 

`get_temp = dht_read_float_data(DHT_TYPE_DHT22, SENSOR_PIN, &humidity_value, &temperature_value);`

and make the following change:  `DHT_TYPE_DHT22 >> DHT_TYPE_DHT11`

After flashing, I also had pairing problems. Make sure you erased flash before flashing. The pairing problem seems to go away after a reboot. If still have issues, please post your serial captured and let me know which example did you try (multiple_sensors or multiple_sensors_ac).

**Comment by renandw** [comment]
Thanks a lot. It works flawlessly!!
Thanks a lot for your work

**Comment by peros550** [comment]
You are welcome :)
