### ISSUE TITLE
lux backwards

### ISSUE THREAD

**Issue by knobby888** [peros550/esp-homekit-multiple-sensors#6]
Hi loving the sensor works well but I'm having a issue with the lux sensor reading backwards. I am using a photo diode and it is reading but i get 0 lux when in light and 1024 in the dark. Also is there a way to get it to post every 5 seconds and not every 10 seconds.

**Comment by vsidlu** [comment]
I had the same thing. Before compiling I made changes in file - multiple_sensors.c
Search for Light measurement section and switch light_value and 1024 places.

currentAmbientLightLevel.value.float_value = (light_value - 1024);
		 homekit_characteristic_notify(&currentAmbientLightLevel, HOMEKIT_FLOAT((light_value - 1024))); 

hope it helps!

**Comment by knobby888** [comment]
I will give it a try thank you

**Comment by knobby888** [comment]
I have just tried the above it compiles and loads onto the esp but it will no longer pair to my HomeKit it fails to add accessories if i swap them back it pairs first time.

**Comment by vsidlu** [comment]
can you try without 1024 -

currentAmbientLightLevel.value.float_value = (light_value);
homekit_characteristic_notify(&currentAmbientLightLevel, HOMEKIT_FLOAT((light_value)));

**Comment by knobby888** [comment]
This has fixed the issue thanks for your time and help much appreciated.
